a = input ('Digite algo:')
print ('O tipo primiitivo de', a, 'é', type (a))
print ('O termo digitado é númerico?', a.isnumeric ())
print ('O termo digitado é alfabético?', a.isalpha ())
print ('O termo digitado é alfanumeŕico?', a.isalnum ())