v = int (input ('Digite um núemero:'))
print ('Segue a tabela para o valor digitado')
print ('{} x {} = {}'.format(v, 1, v*1))
print ('{} x {} = {}'.format(v, 2, v*2))
print ('{} x {} = {}'.format(v, 3, v*3))
print ('{} x {} = {}'.format(v, 4, v*4))
print ('{} x {} = {}'.format(v, 5, v*5))
print ('{} x {} = {}'.format(v, 6, v*6))
print ('{} x {} = {}'.format(v, 7, v*7))
print ('{} x {} = {}'.format(v, 8, v*8))
print ('{} x {} = {}'.format(v, 9, v*9))
print ('{} x {} = {}'.format(v, 10, v*10))